export const videos =[

    {
        id:1,
        categoriesId:3,
        titre:"bienvenu",
        description:"bla bla",
        image:"url",
        tendance:0,
        date:"12/02/2002",
    },
    {
        id:2,
        categoriesId:5,
        titre:"bienvenu chez les nulls",
        description:"Personne ne nait null mais tout le monde l'est.",
        image:"url",
        tendance:0,
        date:"12/02/2002",
    },
    {
        id:3,
        categoriesId:2,
        titre:"Tete mullet",
        description:"Expression trés populaire en martinique et aussi dans les antilles.",
        image:"url",
        tendance:0,
        date:"12/02/2002",
    },
    {
        id:4,
        categoriesId:2,
        titre:"bienvenu a grand riviere",
        description:"commune de Monsieur Million Stéphen ",
        image:"url",
        tendance:0,
        date:"12/02/2002",
    },
    {
        id:5,
        categoriesId:2,
        titre:"bienvenu a l'imfpa",
        description:"Centre de dev personnel ",
        image:"url",
        tendance:0,
        date:"12/02/2002",
    },
    {
        id:6,
        categoriesId:2,
        titre:"Devenir dev",
        description:"Developper web, un metier d'avenir",
        image:"url",
        tendance:0,
        date:"12/02/2002",
    },
    {
        id:7,
        categoriesId:2,
        titre:"Bien etre dans les bois",
        description:"bla bla, pendant que le loup n'y est pas !",
        image:"url",
        tendance:0,
        date:"12/02/2002",
    },
    {
        id:8,
        categoriesId:2,
        titre:"Bien etre dans les bois",
        description:"la chasse est ouverte",
        image:"url",
        tendance:0,
        date:"12/02/2002",
    },
    {
        id:9,
        categoriesId:2,
        titre:"Bien etre dans les bois",
        description:"La nature le seul remede sur terre.",
        image:"url",
        tendance:0,
        date:"12/02/2002",
    },
    {
        id:10,
        categoriesId:2,
        titre:"Bien etre à la plage",
        description:"l'été offre ces belles plages cette période festival",
        image:"url",
        tendance:0,
        date:"12/02/2002",
    },

]